export const plans = [
  {
    id: "free",
    name: "Free",
    price: 0,
    period: "month",
    description: "Everything to get started",
    features: ["Users: 1", "Custom domains: 3", "Branded links: 3", "Tracked clicks: 5"],
    highlighted: false,
  },
  {
    id: "hobby",
    name: "Hobby",
    monthly_price: 1,
    yearly_price: 10,
    period: "month",
    description: "Perfect for personal projects",
    features: ["Country targeting", "Referrer hiding", "Tracked clicks: 100,000/mo"],
    highlighted: false,
  },
  {
    id: "pro",
    name: "Pro",
    monthly_price: 1,
    yearly_price: 10,
    period: "month",
    description: "For professionals & consultants",
    features: [
      "Password protection",
      "Link expiration",
      "Link cloaking",
      "Unlimited tracked clicks",
    ],
    highlighted: false,
  },
  {
    id: "team",
    name: "Team",
    monthly_price: 1,
    yearly_price: 10,
    period: "month",
    description: "For growing teams",
    features: [
      "City/region targeting",
      "Mobile deep links",
      "End-to-end encryption",
      "99.9% uptime SLA",
    ],
    highlighted: true, // BEST OFFER
  },
  {
    id: "enterprise",
    name: "Enterprise",
    monthly_price: 1,
    yearly_price: 10,
    period: "month",
    description: "For large-scale operations",
    features: ["Multiple teams", "Single sign-on (SSO)", "Raw data export to S3"],
    highlighted: false,
  },
];
